#
# Create a custom JLink runtime
#
FROM adoptopenjdk:16 AS builder
RUN cd /usr/local && \
    curl -O https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
    tar xfvz apache-maven-3.6.3-bin.tar.gz && \
    rm apache-maven-3.6.3-bin.tar.gz
COPY . /root
RUN export PATH=$PATH:/usr/local/apache-maven-3.6.3/bin && \
    cd /root && \
    mvn --no-transfer-progress clean install

#
# Create a zip file for Azure Functions using custom handlers with the JLink runtime
#
FROM debian:10-slim AS zip
RUN apt-get update && apt-get install -y zip
COPY --from=builder /root/target/jlink /usr/local/functions/helloworld
COPY --from=builder /root/src/main/functions /usr/local/functions
RUN cd /usr/local/functions ; zip -r ../functions.zip *
