#
# Run the build through GraalVM
#
FROM debian:10-slim AS builder
RUN cd /usr/local && \
    apt-get -y update && \
    apt-get -y install build-essential curl libz-dev zlib1g-dev && \
    curl -O https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
    tar xfvz apache-maven-3.6.3-bin.tar.gz && \
    rm apache-maven-3.6.3-bin.tar.gz && \
    curl -O -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java16-linux-amd64-21.1.0.tar.gz && \
    tar xfvz graalvm-ce-java16-linux-amd64-21.1.0.tar.gz && \
    rm graalvm-ce-java16-linux-amd64-21.1.0.tar.gz
COPY . /root
RUN export PATH=$PATH:/usr/local/graalvm-ce-java16-21.1.0/bin:/usr/local/apache-maven-3.6.3/bin && \
    gu install native-image && \
    cd /root && \
    export MAVEN_OPTS=-Xmx4G && \
    mvn --no-transfer-progress -P graalvm clean install

#
# Create a slim Debian image with the GraalVM helloworld binary
#
FROM debian:10-slim
COPY --from=builder /root/target/helloworld /usr/local/bin/helloworld
EXPOSE 8080
CMD ["/usr/local/bin/helloworld"]
